target=output


#command links o file
output: hello.o
	g++ -o hello hello.o
#doesnt know the h files


# #creates o
#hello.o: hello.cpp
# 	g++ -c hello.cpp

# output: hello.cpp
# 	g++ -o hello hello.cpp

clean: 
	rm -f *.o hello 